---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: talos-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: talos-cluster-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: FreeboxCluster
    name: talos-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: FreeboxCluster
metadata:
  name: talos-cluster
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 192.168.1.202
    port: 6443
