---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-cluster-cp
  namespace: default
spec:
  version: v1.34.1
  replicas: 1
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: FreeboxMachineTemplate
    name: talos-cluster-cp
    namespace: default
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.11.5
      configPatches:
        - op: add
          path: /machine/install
          value:
            disk: /dev/vda
            image: ghcr.io/siderolabs/installer:v1.11.5
        - op: add
          path: /machine/network
          value:
            interfaces:
              - deviceSelector:
                  physical: true
                dhcp: true
                vip:
                  ip: 192.168.1.202
        # - op: add
        #   path: /cluster/network/cni
        #   value:
        #     name: none
        - op: add
          path: /cluster/allowSchedulingOnControlPlanes
          value: true
        # - op: add
        #   path: /machine/kubelet/extraArgs
        #   value:
        #     cloud-provider: external
        #     rotate-server-certificates: "true"
        # - op: add
        #   path: /cluster/externalCloudProvider
        #   value:
        #     enabled: true
        #     manifests:
        #       - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml
        #       - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
        # - op: add
        #   path: /machine/features/kubernetesTalosAPIAccess
        #   value:
        #     enabled: true
        #     allowedRoles:
        #       - os:reader
        #     allowedKubernetesNamespaces:
        #       - kube-system
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: FreeboxMachineTemplate
metadata:
  name: talos-cluster-cp
  namespace: default
spec:
  template:
    spec:
      # VM name on the Freebox
      name: talos-cp
      # Number of vCPUs
      vcpus: 2
      # RAM in MB
      memoryMB: 4096
      # Target disk size in bytes (10GiB)
      diskSizeBytes: 10737418240
      # Talos image URL (will be downloaded by the controller)
      imageURL: https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.11.5/nocloud-arm64.raw.xz
